//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cy.RolePermission.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int Log_Id { get; set; }
        public Nullable<System.DateTime> Log_DateTime { get; set; }
        public int User_Id { get; set; }
        public string Action_Code { get; set; }
        public string Operation_Type { get; set; }
        public string Remark { get; set; }
        public string SystemCode { get; set; }
        public string ClassName { get; set; }
        public Nullable<int> UserInfoId { get; set; }
    
        public virtual UserInfo UserInfo { get; set; }
    }
}
